### ISSUE TITLE
python-broadlink not support python3

### ISSUE THREAD

**Issue by blackhu** [mjg59/python-broadlink#143]
你好：
    由于使用python-broadlink对接homeassistant，但是homeassistant运行在python3环境中。所以python-broadlink也运行于python3中了 。但是配置完成后，home-assistant.log有错误，如下：
----------------
2018-01-14 10:10:14 WARNING (MainThread) [homeassistant.bootstrap] Python 3.4 support has been deprecated and will be removed in the beginning of 2018. Please upgrade Python or your operating system. More info: https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/
2018-01-14 10:10:16 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=19 from 2018-01-14 02:00:56.606075)
2018-01-14 10:10:17 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform broadlink
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/broadlink.py", line 174, in setup_platform
    broadlink_device.auth()
  File "/srv/homeassistant/lib/python3.4/site-packages/broadlink/__init__.py", line 203, in auth
    response = self.send_packet(0x65, payload)
  File "/srv/homeassistant/lib/python3.4/site-packages/broadlink/__init__.py", line 258, in send_packet
    payload = self.encrypt(payload)
  File "/srv/homeassistant/lib/python3.4/site-packages/broadlink/__init__.py", line 162, in encrypt_pyaes
    return "".join([aes.encrypt(bytes(payload[i:i+16])) for i in range(0, len(payload), 16)])
TypeError: sequence item 0: expected str instance, bytes found
----------------
通过我进行了 一步步调试，发现/python3.4/site-packages/broadlink/__init__.py，中的171行，    return "".join([aes.encrypt(bytes(payload[i:i+16])) for i in range(0, len(payload), 16)])语句不兼容python3，poc如下：
![image](https://user-images.githubusercontent.com/5728454/34917335-f6e7ddfe-f97f-11e7-82a4-043dec4f6c09.png)

**Comment by thias** [comment]
The changes in #95 should fix this. It did for me with python 3.6.
