### ISSUE TITLE
Error from pyaes

### ISSUE THREAD

**Issue by ekzoss** [mjg59/python-broadlink#227]
Excited about trying this, but getting some error right off the bat with auth:
Traceback (most recent call last):
  File "./broadlink_discovery", line 25, in <module>
    if device.auth():
  File "/data/ZossNet/python-broadlink/broadlink/__init__.py", line 213, in auth
    response = self.send_packet(0x65, payload)
  File "/data/ZossNet/python-broadlink/broadlink/__init__.py", line 269, in send_packet
    payload = self.encrypt(payload)
  File "/data/ZossNet/python-broadlink/broadlink/__init__.py", line 171, in encrypt_pyaes
    aes = pyaes.AESModeOfOperationCBC(self.key, iv = bytes(self.iv))
  File "/data/ZossNet/python-broadlink/pyaes-master/pyaes/aes.py", line 385, in __init__
    AESBlockModeOfOperation.__init__(self, key)
  File "/data/ZossNet/python-broadlink/pyaes-master/pyaes/aes.py", line 304, in __init__
    self._aes = AES(key)
  File "/data/ZossNet/python-broadlink/pyaes-master/pyaes/aes.py", line 148, in __init__
    tk = [ struct.unpack('>i', key[i:i + 4])[0] for i in xrange(0, len(key), 4) ]
struct.error: unpack requires a string argument of length 4

Can you help ?

**Comment by ekzoss** [comment]
I resolved this by changing the following to convert bytearray key to str:
  def encrypt_pyaes(self, payload):
    #aes = pyaes.AESModeOfOperationCBC(self.key, iv = bytes(self.iv))
    aes = pyaes.AESModeOfOperationCBC(str(self.key), iv = bytes(self.iv))
    return b"".join([aes.encrypt(bytes(payload[i:i+16])) for i in range(0, len(payload), 16)])

  def decrypt_pyaes(self, payload):
    #aes = pyaes.AESModeOfOperationCBC(self.key, iv = bytes(self.iv))
    aes = pyaes.AESModeOfOperationCBC(str(self.key), iv = bytes(self.iv))
    return b"".join([aes.decrypt(bytes(payload[i:i+16])) for i in range(0, len(payload), 16)])

This is python 2.7 maybe that's why.. ?
