### ISSUE TITLE
socket.timeout: timed out for bg1 socket

### ISSUE THREAD

**Issue by alinelena** [mjg59/python-broadlink#328]
I have a bg1 that I am testing at the moment.... is close to the router so there are no connection issues but I get socket timeout and nothing happens.

```
2020-03-24 18:07:44,968] DEBUG Connected to 'BG1' Broadlink device at '192.168.1.120' (MAC f6:53:fc:42:f7:c8) and started listening for commands at MQTT topic having prefix 'broadlink/' 
[2020-03-24 18:07:44,983] DEBUG Connected to MQTT broker, subscribing to topic broadlink/#
[2020-03-24 18:08:16,009] DEBUG Sending BG1 pwr '1' to topic 'broadlink/state/pwr'
[2020-03-24 18:08:16,011] DEBUG Sending BG1 pwr1 '0' to topic 'broadlink/state/pwr1'
[2020-03-24 18:08:16,012] DEBUG Sending BG1 pwr2 '1' to topic 'broadlink/state/pwr2'
[2020-03-24 18:08:16,013] DEBUG Sending BG1 maxworktime '0' to topic 'broadlink/state/maxworktime'
[2020-03-24 18:08:16,013] DEBUG Sending BG1 maxworktime1 '0' to topic 'broadlink/state/maxworktime1'
[2020-03-24 18:08:16,015] DEBUG Sending BG1 maxworktime2 '0' to topic 'broadlink/state/maxworktime2'
[2020-03-24 18:08:16,015] DEBUG Sending BG1 idcbrightness '100' to topic 'broadlink/state/idcbrightness'
[2020-03-24 18:08:34,372] DEBUG Received MQTT message broadlink/power/1 on
[2020-03-24 18:08:34,372] DEBUG Setting power state of socket 1 to True
[2020-03-24 18:08:42,284] DEBUG Received MQTT message broadlink/power/1 off
[2020-03-24 18:08:42,285] DEBUG Setting power state of socket 1 to False
[2020-03-24 18:08:52,298] ERROR Error
Traceback (most recent call last):
  File "./mqtt.py", line 145, in on_message
    device.set_state(pwr1=state)
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 391, in set_state
    response = self.send_packet(0x6a, packet)
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 286, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out
[2020-03-24 18:08:53,876] DEBUG Received MQTT message broadlink/power/1 on
[2020-03-24 18:08:53,876] DEBUG Setting power state of socket 1 to True
[2020-03-24 18:08:55,302] ERROR Error
Traceback (most recent call last):
  File "./mqtt.py", line 546, in broadlink_bg1_state_timer
    state = device.get_state()
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 370, in get_state
    response = self.send_packet(0x6a, packet)
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 286, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out
[2020-03-24 18:09:04,311] ERROR Error
Traceback (most recent call last):
  File "./mqtt.py", line 145, in on_message
    device.set_state(pwr1=state)
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 391, in set_state
    response = self.send_packet(0x6a, packet)
  File "/home/drFaustroll/venv/broadlink/lib64/python3.8/site-packages/broadlink/__init__.py", line 286, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out

```

any ideas?
the device details are here... 
```
{"PID":"...","DID":"...","Access to the cloud":"....","MAC":"c8:f7:42:fc:53:f6","Firmware":"46043","device IP":"192.168.1.120@80"}
```

**Comment by felipediel** [comment]
Did you block internet access?
