### ISSUE TITLE
Authentication faliure

### ISSUE THREAD

**Issue by chazeon** [mjg59/python-broadlink#403]
Hi,

I am getting an authentication failure
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import broadlink
>>> devices = broadlink.discover(timeout=5)
>>> devices
[]
>>> devices = broadlink.discover(timeout=5)
>>> devices
[<broadlink.rm4 object at 0xb6245110>]
>>> devices
[<broadlink.rm4 object at 0xb6245110>]
>>> devices
[<broadlink.rm4 object at 0xb6245110>]
>>> devices[0].auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/python-broadlink/broadlink/__init__.py", line 271, in auth
    check_error(response[0x22:0x24])
  File "/home/pi/python-broadlink/broadlink/exceptions.py", line 97, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: Authentication failed
```
And my device is actually a Broadlink mini 3.

The 0x22 and 0x23 bytes are 255.

I can use the device from my iPhone APP.
Device firmware version V44057.

Any thoughts?

**Comment by chazeon** [comment]
Problem solved by resetting the device.
