### ISSUE TITLE
TypeError: initializer for ctype 'unsigned char *' must be a cdata pointer, not bytearray

### ISSUE THREAD

**Issue by psyntium** [mjg59/python-broadlink#499]
I'm running on MacOS.

When trying to run discovery:
```bash
$ ./broadlink_discovery 
Discovering...
Traceback (most recent call last):
  File "./broadlink_discovery", line 16, in <module>
    if device.auth():
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 197, in auth
    response = self.send_packet(0x65, payload)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 303, in send_packet
    payload = self.encrypt(payload)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 162, in encrypt
    return encryptor.update(payload) + encryptor.finalize()
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 135, in update_into
    data, len(data))
TypeError: initializer for ctype 'unsigned char *' must be a cdata pointer, not bytearray
```

Same when using direct python2 or python3:
```bash
>>> import broadlink
>>> broadlink.setup('XXXXXX', 'XXXXXX', 3)
>>> devices = broadlink.discover(timeout=5)
>>> devices[0]
<rm4: Broadlink RM4 pro (0x6026) at 192.168.0.180:80 | a0:43:b0:18:d9:1c | IR RF Remote | Unlocked>
>>> devices[0].auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 197, in auth
    response = self.send_packet(0x65, payload)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 303, in send_packet
    payload = self.encrypt(payload)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/broadlink/device.py", line 162, in encrypt
    return encryptor.update(payload) + encryptor.finalize()
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/Users/aiman/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 135, in update_into
    data, len(data))
TypeError: initializer for ctype 'unsigned char *' must be a cdata pointer, not bytearray
```

**Comment by KTibow** [comment]
Try python3.9, and also try upgrading the `cryptography` lib.
