### ISSUE TITLE
Trying to discover device outside current subnet

### ISSUE THREAD

**Issue by Daan12345678** [mjg59/python-broadlink#543]
Tried discovering a device outside the subnet my pc is using. Got an error.
```
❯ ./broadlink_discovery --ip 192.168.2.166                                                                                                            ─╯
Discovering...
Traceback (most recent call last):
  File "/home/daan/personal/broadlink/python-broadlink/cli/./broadlink_discovery", line 14, in <module>
    devices = broadlink.discover(timeout=args.timeout, local_ip_address=args.ip, discover_ip_address=args.dst_ip)
  File "/home/daan/.local/lib/python3.9/site-packages/broadlink/__init__.py", line 150, in discover
    return [gendevice(*resp) for resp in responses]
  File "/home/daan/.local/lib/python3.9/site-packages/broadlink/__init__.py", line 150, in <listcomp>
    return [gendevice(*resp) for resp in responses]
  File "/home/daan/.local/lib/python3.9/site-packages/broadlink/device.py", line 29, in scan
    conn.bind((local_ip_address, 0))
OSError: [Errno 99] Cannot assign requested address
```
ICMP for example is no issue
```
PING 192.168.2.166 (192.168.2.166) 56(84) bytes of data.
64 bytes from 192.168.2.166: icmp_seq=1 ttl=254 time=408 ms
64 bytes from 192.168.2.166: icmp_seq=2 ttl=254 time=4.46 ms
```

Expected result:
Program scans fine outside subnet

**Comment by KTibow** [comment]
All it's doing is calling another library. Are you sure that's the right parameter?

**Comment by Daan12345678** [comment]
You are correct, sorry for bothering you with this issue. 
Should have used this command:
```
./broadlink_discovery --dst-ip 192.168.2.166 
```
