### ISSUE TITLE
Python 3.4 Winpython

### ISSUE THREAD

**Issue by tyjtyj** [mjg59/python-broadlink#8]
Hi, This is a great project

I need some help on this. I am not a py programmer. 

Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    device.auth()
  File "broadlink__init__.py", line 92,
in auth
    payload[0x30] = 'T'
TypeError: an integer is required

demo.py content
import broadlink

device = broadlink.rm2()
device.discover()
device.auth()

I try changing 
payload[0x30] = int(ord('T'))
payload[0x30] = hex(ord('T'))
both dont work.

**Comment by tyjtyj** [comment]
nvm. i downgrade back to winpython 2.7 and it works perfectly
