### ISSUE TITLE
Long Wifi Password results in "IndexError: bytearray index out of range"

### ISSUE THREAD

**Issue by Jamolo5** [mjg59/python-broadlink#815]
When trying to set up a device, I run the command:
`broadlink.setup('mywifi','some37characterlongpassword',3,ip_address='192.168.1.255')`
Which results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jamo/.local/lib/python3.10/site-packages/broadlink/__init__.py", line 318, in setup
    payload[(pass_start + pass_length)] = ord(letter)
IndexError: bytearray index out of range
```

The original reason I was wanting to use this package is because the Broadlink app doesn't support my wifi password length

**Comment by ChrisAcrobat** [comment]
I'm having the same problem and with the same reason.

**Comment by ChrisAcrobat** [comment]
The device has a 32 character limit. #235 👎
